name: Build and Push Backend Docker Image to AWS ECR

on:
  push:
    branches:
      - develop
    paths:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActionsSession

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials

    - name: Build and Push Docker Image using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build app
        docker tag ${{ steps.login-ecr.outputs.registry }}:${{ github.sha }} ${{ secrets.BACKEND_ECR_REPOSITORY_URL }}:${{ github.sha }}
        docker push ${{ secrets.BACKEND_ECR_REPOSITORY_URL }}:${{ github.sha }}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DB_LOCAL_PASSWORD: ${{ secrets.DB_LOCAL_PASSWORD }}
        DB_LOCAL_DBNAME: ${{ secrets.DB_LOCAL_DBNAME }}
        PORT: "5050"
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
